In [1]:
import numpy as np
import scipy.integrate
import matplotlib.pyplot as plt
import numdifftools as nd

In [2]:
d = 1
q_0 = 1
w = np.pi
e = 1
c = 1
epsilon_0 = 1
mu_0 = 1

In [3]:
def q(t,d,w,e,q_0):
    return q_0*np.cos(w*t)
def i(t,d,w,e,q_0):
    return -2*q_0*w*np.sin(w*t)*np.array([0,0,1], float)

In [4]:
def A(r,t):
    k = scipy.integrate.quad_vec(
        lambda r_p: i(t-np.linalg.norm(r-r_p)/c,d,w,e,q_0)/np.linalg.norm(r-r_p),
        -d/2,
        d/2
    )
    return mu_0/(4*np.pi)*k[0]
def phi(r,t):
    r_p = d/2*np.array([[0,0,1],[0,0,-1]],float)
    return sum([((-1)**i)*(1/(4*np.pi*epsilon_0))*
                q(t-np.linalg.norm(r-r_p[i])/c,d,w,e,q_0)/np.linalg.norm(r-r_p[i]) for i in range(2)])

In [5]:
A(np.array([0,0,0.1]), 0)

array([0.        , 0.        , 1.03437504])

In [6]:
phi(np.array([0,0,0.1]), 0)

0.10246162948786103

In [7]:
def E(x, t):
    return -nd.Gradient(lambda x: phi(x,t))(x) - nd.Gradient(lambda t: A(x,t))(t)

In [8]:
def curl(f,x):
    jac = nd.Jacobian(f)(x)
    return np.array([jac[2,1]-jac[1,2],jac[0,2]-jac[2,0],jac[1,0]-jac[0,1]])

def B(x,t):
    return curl(lambda x: A(x,t), x)

In [9]:
B(np.array([3,2,10]),1)

array([ 0.0055372 , -0.00693738,  0.        ])

In [10]:
E(np.array([3,2,0.1]),1)

array([ 0.00320329,  0.00213552, -0.03243752])

In [11]:
from manim import *

In [12]:
class

SyntaxError: invalid syntax (<ipython-input-12-5ef9dc4cb34b>, line 1)