In [2]:
from manim import *
import Dipole_Sim

In [20]:
Dipole_Sim.E(UP,1)

array([-0.        , -0.        ,  1.01998738])

In [21]:
from manim import *

In [46]:
def get_rgb_gradient_function(
    min_value: int = 0,
    max_value: int = 1,
    colors: list = [BLUE, RED],
    flip_alphas: bool = True,  # Why?
):
    rgbs = np.array(list(map(color_to_rgb, colors)))

    def func(values: np.ndarray):
        alphas = inverse_interpolate(min_value, max_value, np.array(values))
        alphas = np.clip(alphas, 0, 1)
        # if flip_alphas:
        #     alphas = 1 - alphas
        scaled_alphas = alphas * (len(rgbs) - 1)
        indices = scaled_alphas.astype(int)
        next_indices = np.clip(indices + 1, 0, len(rgbs) - 1)
        inter_alphas = scaled_alphas % 1
        inter_alphas = inter_alphas.repeat(3).reshape((len(indices), 3))
        result = interpolate(rgbs[indices], rgbs[next_indices], inter_alphas)
        return result

    return func

In [77]:
colors = [BLUE_E, GREEN, YELLOW, RED]
class Field(ThreeDScene):
    def construct(self):
        #v = ArrowVectorField(lambda x: Dipole_Sim.B(x,0), delta_x=2, delta_y=2)
#         v = VGroup(
#             *[Vector(Dipole_Sim.B(x,0),).move_to(x) for x in
#              np.transpose(np.array(np.meshgrid(np.arange(-1,1,0.5),np.arange(-1,1,0.5),np.arange(-1,1,0.5))),
#                           [1,2,3,0]).reshape((-1,3))
#             ]
#             )
#         self.add(v)
         
        vector = Vector(np.array([1,2,0]))
        vector.rotate_about_origin(60*DEGREES,UP)
        norm = vector.get_length()
        vector.set_color(
            rgb_to_color(
            get_rgb_gradient_function(
            0,2,colors,flip_alphas=False
            )(np.array([norm]))[0]))
        self.add(vector)
        self.add(Axes())
        vector.set_length(1)
        self.move_camera(90*DEGREES, 45*DEGREES, 4, run_time=5)

In [ ]:
class 3DVectorField(VectorField, z_min, z_max):
    def __init__(self, delta_z=0.5,**kwargs):
        self.delta_z = delta_z
        self.z_min = z_min
        self.z_max = z_max
        VectorField.__init__(self, **kwargs)

Object `VectorField.get_vector` not found.


In [78]:
%manim -ql Field 

In [19]:
[Dipole_Sim.B(x,0) for x in
np.transpose(np.array(np.meshgrid(np.arange(-1,1,0.1),np.arange(-1,1,0.1),np.arange(-1,1,0.1))), [1,2,3,0])
]

KeyboardInterrupt: 

In [31]:
[Dipole_Sim.B(x,0) for x in
np.transpose(np.array(np.meshgrid(np.arange(-1,1,1),np.arange(-1,1,1),np.arange(-1,1,1))), [1,2,3,0]).reshape((-1,3))
]

[array([ 0.01750154, -0.01750154,  0.        ]),
 array([ 0.1757458, -0.1757458,  0.       ]),
 array([0.1757458 , 0.23819191, 0.        ]),
 array([1.06136053, 0.28024307, 0.        ]),
 array([-0.23819191, -0.1757458 ,  0.        ]),
 array([-0.28024307, -1.06136053,  0.        ]),
 array([-0.28024307,  0.28024307,  0.        ]),
 array([0., 0., 0.])]

In [26]:
np.transpose(np.array(np.meshgrid(np.arange(-1,1,0.5),np.arange(-1,1,0.5),np.arange(-1,1,0.5))),
                          [1,2,3,0])

array([[[[-1. , -1. , -1. ],
         [-1. , -1. , -0.5],
         [-1. , -1. ,  0. ],
         [-1. , -1. ,  0.5]],

        [[-0.5, -1. , -1. ],
         [-0.5, -1. , -0.5],
         [-0.5, -1. ,  0. ],
         [-0.5, -1. ,  0.5]],

        [[ 0. , -1. , -1. ],
         [ 0. , -1. , -0.5],
         [ 0. , -1. ,  0. ],
         [ 0. , -1. ,  0.5]],

        [[ 0.5, -1. , -1. ],
         [ 0.5, -1. , -0.5],
         [ 0.5, -1. ,  0. ],
         [ 0.5, -1. ,  0.5]]],


       [[[-1. , -0.5, -1. ],
         [-1. , -0.5, -0.5],
         [-1. , -0.5,  0. ],
         [-1. , -0.5,  0.5]],

        [[-0.5, -0.5, -1. ],
         [-0.5, -0.5, -0.5],
         [-0.5, -0.5,  0. ],
         [-0.5, -0.5,  0.5]],

        [[ 0. , -0.5, -1. ],
         [ 0. , -0.5, -0.5],
         [ 0. , -0.5,  0. ],
         [ 0. , -0.5,  0.5]],

        [[ 0.5, -0.5, -1. ],
         [ 0.5, -0.5, -0.5],
         [ 0.5, -0.5,  0. ],
         [ 0.5, -0.5,  0.5]]],


       [[[-1. ,  0. , -1. ],
         [-1. ,  0. , -